### ISSUE TITLE
Bug when dataclasses produce <factory> as output somewhere

### ISSUE THREAD

**Issue by Yajo** [pawamoy/mkdocstrings#222]
**Describe the bug**

You can see [this log](https://readthedocs.org/projects/copier/builds/12937443/) when building docs for [this code](https://github.com/copier-org/copier/tree/910e0d84523da5360e79c98193692fc64303f07d) (https://github.com/copier-org/copier/pull/314):

<details>

```
➤ poe docs
Poe => mkdocs serve
INFO    -  Building documentation... 
INFO    -  MERMAID2  - Initialization arguments: {'flowchart': {'curve': 'basis'}} 
INFO    -  MERMAID2  - Using javascript library (8.8.0):
   https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js 
INFO    -  Cleaning site directory 
WARNING -  mkdocstrings.handlers.python: Couldn't read source for 'copier.main.Worker.__eq__': could not get source code 
WARNING -  mkdocstrings.handlers.python: Couldn't read source for 'copier.main.Worker.__init__': could not get source code 
WARNING -  mkdocstrings.handlers.python: Couldn't read source for 'copier.main.Worker.__repr__': could not get source code 
WARNING -  mkdocstrings.handlers.python: copier.main.Worker.render_folder: No type annotation for parameter 'src_path' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'answers_file' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'exclude' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'skip_if_exists' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'tasks' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'envops' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'pretend' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'force' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'quiet' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'cleanup_on_error' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'vcs_ref' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'only_diff' 
WARNING -  mkdocstrings.handlers.python: copier.main.copy: No type annotation for parameter 'use_prereleases' 
ERROR   -  Error reading page 'reference/main.md': string index out of range 
Traceback (most recent call last):
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocstrings/extension.py", line 215, in process_block
    xml_contents = XML(ENTITIES + rendered)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 54, column 420

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/home/yajo/mydevel/copier/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocstrings/extension.py", line 155, in run
    xml_element = self.process_block(identifier, str(block))
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocstrings/extension.py", line 217, in process_block
    log_xml_parse_error(str(error), rendered)
  File "/var/home/yajo/mydevel/copier/.venv/lib/python3.9/site-packages/mkdocstrings/extension.py", line 288, in log_xml_parse_error
    character = line[columnno]
IndexError: string index out of range
```

</details>

The logs seem to indicate a failure while trying to indicate the failure, so not much helpful, but debugging in a little bit, it seems mkdocs is processing an HTML that contains this:

    <p>Worker(src_path: Optional[str] = None, dst_path: pathlib.Path = '.', answers_file: Optional[copier.types.RelativePath] = None, cleanup_on_error: bool = True, data: Dict[str, Any] = <factory>, envops: dict = <factory>, exclude: Sequence[str] = (), force: bool = False, pretend: bool = False, quiet: bool = False, skip_if_exists: Sequence[str] = (), use_prereleases: bool = False, vcs_ref: Optional[str] = None)</p>

Of course, those `<factory>`, which I don't know where they come from, are not escaped.

So, on one side the error reporting is broken, and on the other side there's an error that shouldn't have happened.

**To Reproduce**
1. Clone https://github.com/copier-org/copier/tree/910e0d84523da5360e79c98193692fc64303f07d
2. `poetry install -E docs`
3. `mkdocs serve`

**Expected behavior**
Serving docs.

**Information (please complete the following information):**
- OS: Linux
- `mkdocstrings` version: 0.13.6

**Additional context**
It seems those `<factory>` come from some [pydantic dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/).

**Comment by oprypin** [comment]
This is fixed on master with https://github.com/pawamoy/mkdocstrings/pull/188

**Comment by pawamoy** [comment]
And will be published in 0.15 (not sure when, but soon I hope).

**Comment by oprypin** [comment]
Hold up, it's already included in 0.14.0, you just need to upgrade :D

**Comment by pawamoy** [comment]
Oh boy, just as you said on gitter, we lost track of the PRs haha

**Comment by Yajo** [comment]
I'm afraid it still fails: https://readthedocs.org/projects/copier/builds/12943117/

**Comment by oprypin** [comment]
😖  I mixed them up again, it's actually this pull request https://github.com/pawamoy/mkdocstrings/pull/209 and indeed it hasn't made it into a release. But I checked locally that it works on *master*.

**Comment by pawamoy** [comment]
I'll close since it's already fixed in master. Will try to release soon (there some issues on the roadmap that need to be addressed as well for 0.15).
